name: dl_vision
channels:
        - conda-forge
        - pytorch
dependencies:
        - python=3.7
        - pip
        - numpy
        - black
        - pandas 
        - matplotlib
        - jupyter
        - jupyterlab
        - pytorch >=1.4
        - torchvision>=0.5
        - tqdm
        - opencv
        - pip:
          - torchviz
